# Generated by Django 5.0.1 on 2024-02-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='predestrian_infrastructure',
            new_name='pedestrian_infrastructure',
        ),
    ]
